# Generated by Django 3.2.10 on 2022-01-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineChart', '0002_auto_20220124_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team1',
            new_name='T1Point',
        ),
        migrations.RenameModel(
            old_name='Team2',
            new_name='T2Point',
        ),
    ]
