# Generated by Django 3.2.10 on 2022-01-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineChart', '0004_auto_20220124_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='T2Points',
            new_name='T1Score',
        ),
        migrations.RenameModel(
            old_name='T1Points',
            new_name='T2Score',
        ),
    ]
