# Generated by Django 3.2.10 on 2022-01-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineChart', '0005_auto_20220124_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t1score',
            old_name='points',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='t2score',
            old_name='points',
            new_name='point',
        ),
    ]
