# Generated by Django 3.2.10 on 2022-01-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineChart', '0008_auto_20220128_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T1A', models.IntegerField()),
                ('T1AS', models.IntegerField()),
                ('T1D', models.IntegerField()),
                ('T1DS', models.IntegerField()),
                ('T1ADS', models.IntegerField()),
                ('T1ASQ', models.IntegerField()),
                ('T1DSQ', models.IntegerField()),
                ('T1ADSQ', models.IntegerField()),
                ('T2A', models.IntegerField()),
                ('T2AS', models.IntegerField()),
                ('T2D', models.IntegerField()),
                ('T2DS', models.IntegerField()),
                ('T2ADS', models.IntegerField()),
                ('T2ASQ', models.IntegerField()),
                ('T2DSQ', models.IntegerField()),
                ('T2ADSQ', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Scores',
        ),
    ]
